theme: jekyll-theme-midnight
title: Melody Hero
description: Nida Pervez: Nidapervez2020@u.northwestern.edu, Alex van der Heijden:vdhalex@u.northwestern.edu, David Wolff:davidwolff2020@u.northwestern.edu Machine Perception of Audio and Music Northwestern University Professor Bryan Pardo
