theme: jekyll-theme-midnight
title: Melody Hero
description: Nida Pervez, Alex van der Heijden, David Wolff 
description: Nidapervez2020@u.northwestern.edu, vdhalex@u.northwestern.edu, davidwolff2020@u.northwestern.edu 
description: Machine Perception of Audio and Music Northwestern University Professor Bryan Pardo
